### ISSUE TITLE
UI issue in the navigation menu

### ISSUE THREAD

**Issue by WarenGonzaga** [algofilipino/homepage#19]
Here's what I see from the dev branch.

![image](https://user-images.githubusercontent.com/15052701/139035575-7f00492b-43c0-4f1d-a4c7-5fcda3d7daae.png)

When pressed;

![image](https://user-images.githubusercontent.com/15052701/139035661-3d71e5e2-6e9a-44ae-b2ef-ec5a6d8b4860.png)

We can't merge the latest changes without this fix.

**Comment by sinsimi12** [comment]
@geeythree  Yes, That is correct could you push a PR?

**Comment by geeythree** [comment]
@sinsimi12 sure!
