### ISSUE TITLE
officer captions

### ISSUE THREAD

**Issue by sinsimi12** [algofilipino/homepage#20]

**Comment by sinsimi12** [comment]
okay, we address it to Communications Department.

**Comment by WarenGonzaga** [comment]
is this done? @felixjeromedelafuente

**Comment by felixjeromedelafuente** [comment]
Hi sir, Marie told me that Jherlet's statement was on a document in Google Drive. I'm not sure what document is being referred to though. I already asked Jherlet about this and currently waiting for a reply. Meanwhile, may I also ask you sir @WarenGonzaga your statement/speech for the website?

**Comment by WarenGonzaga** [comment]
> Hi sir, Marie told me that Jherlet's statement was on a document in Google Drive. I'm not sure what document is being referred to though. I already asked Jherlet about this and currently waiting for a reply. Meanwhile, may I also ask you sir @WarenGonzaga your statement/speech for the website?

Alright, I'll submit it via Team's projects here on our organization. I'll ping you once I have, for the founder's statement please ask Marie specifically. Let her know this is my order. Thanks!

**Comment by WarenGonzaga** [comment]
added my caption...
