### ISSUE TITLE
configuration tailwind replacement

### ISSUE THREAD

**Issue by sinsimi12** [algofilipino/homepage#3]
Fix Tailwind Configuration

**Comment by WarenGonzaga** [comment]
@felixdelafuente is this already fixed? Can you take a look into this?

**Comment by felixdelafuente** [comment]
Hi @WarenGonzaga, yes all the necessary Vanilla CSS are now changed to Tailwind CSS. Minimizing the lines of codes in the CSS file at a minimum.

**Comment by WarenGonzaga** [comment]
@felixdelafuente, alright closing this issue now. Thanks!
